apiVersion: v1
kind: Service
metadata:
  name: gogs-srvc
  labels:
    app: gogs-srvc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: gogs-server
  type: LoadBalancer
