apiVersion: v1
kind: Pod
metadata:
  name : gogs-server
  labels: 
    app: gogs-server
spec:
  containers:
    - name: gogs-server
      image: 598240822331.dkr.ecr.us-east-1.amazonaws.com/grid/gogs
      env:
        - name: APP_NAME
          value: "bedrock-project"
        - name: ORG_NAME
          value: "bedrock"
        - name: SOCAT_LINK
          value: "false"
        - name: ELB_PORT
          value: "80"
        - name: K8_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumeMounts:
        - name: podinfo
          mountPath: /meta
          readOnly: false
      ports:
        - containerPort: 3000
          protocol: TCP
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels.properties"
            fieldRef:
              fieldPath: metadata.labels
  imagePullSecrets:
    - name: regsecret
